# GraphvizForGAP, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("graphvizforgap01.tst");

# doc/_Chapter_Full_Reference.xml:78-89
gap> gv := GraphvizGraph("GraphyMcGraphFace");
<graphviz graph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizGraph(666);
<graphviz graph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# doc/_Chapter_Full_Reference.xml:131-142
gap> gv := GraphvizDigraph("GraphyMcGraphFace");
<graphviz digraph "GraphyMcGraphFace" with 0 nodes and 0 edges>
gap> GraphvizName(gv);
"GraphyMcGraphFace"
gap> GraphvizDigraph(666);
<graphviz digraph "666" with 0 nodes and 0 edges>
gap> gv := GraphvizDigraph();
<graphviz digraph with 0 nodes and 0 edges>
gap> GraphvizName(gv);
""

# doc/_Chapter_Full_Reference.xml:167-178
gap> dot := GraphvizDigraph("The Round Table");;
gap> GraphvizName(dot);
"The Round Table"
gap> n := GraphvizSetAttr(GraphvizAddNode(dot, "A"), "label", "King Arthur");
<graphviz node "A">
gap> GraphvizName(n);
"A"
gap> e := GraphvizAddEdge(dot, "A", "B");;
gap> GraphvizName(e);
"(A, B)"

# doc/_Chapter_Full_Reference.xml:191-192

# doc/_Chapter_Full_Reference.xml:220-231
gap> gv := GraphvizDigraph();
<graphviz digraph with 0 nodes and 0 edges>
gap> context := GraphvizAddContext(gv);
<graphviz context "no_name_1" with 0 nodes and 0 edges>
gap> GraphvizAddNode(context, "a");
<graphviz node "a">
gap> GraphvizNodes(gv);  # There are no nodes in gv directly, only in context
rec(  )
gap> GraphvizNodes(context);
rec( a := <graphviz node "a"> )

# doc/_Chapter_Full_Reference.xml:252-261
gap> gv := GraphvizDigraph();
<graphviz digraph with 0 nodes and 0 edges>
gap> context := GraphvizAddContext(gv);
<graphviz context "no_name_1" with 0 nodes and 0 edges>
gap> GraphvizAddNode(context, "a");
<graphviz node "a">
gap> GraphvizNode(gv, "a");
<graphviz node "a">

# doc/_Chapter_Full_Reference.xml:275-276

# doc/_Chapter_Full_Reference.xml:289-290

# doc/_Chapter_Full_Reference.xml:304-305

# doc/_Chapter_Full_Reference.xml:321-322

# doc/_Chapter_Full_Reference.xml:339-346
gap> gv := GraphvizGraph();;
gap> GraphvizAddEdge(gv, "a", "b");;
gap> GraphvizEdges(gv);
[ <graphviz edge (a, b)> ]
gap> GraphvizEdges(gv, "a", "b");
[ <graphviz edge (a, b)> ]

# doc/_Chapter_Full_Reference.xml:360-366
gap> gv := GraphvizGraph();;
gap> e := GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> GraphvizHead(e);
<graphviz node "a">

# doc/_Chapter_Full_Reference.xml:379-385
gap> gv := GraphvizGraph();;
gap> e := GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> GraphvizTail(e);
<graphviz node "b">

# doc/_Chapter_Full_Reference.xml:407-412
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizSetName(gv, "newname");
<graphviz graph "newname" with 0 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:428-435
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizAddNode(gv, "a");
<graphviz node "a">
gap> gv;
<graphviz graph with 1 node and 0 edges>

# doc/_Chapter_Full_Reference.xml:457-464
gap> gv := GraphvizGraph();
<graphviz graph with 0 nodes and 0 edges>
gap> GraphvizAddEdge(gv, "a", "b");
<graphviz edge (a, b)>
gap> gv;
<graphviz graph with 2 nodes and 1 edge>

# doc/_Chapter_Full_Reference.xml:482-483

# doc/_Chapter_Full_Reference.xml:510-511

# doc/_Chapter_Full_Reference.xml:530-537
gap> gv := GraphvizGraph();;
gap> GraphvizAddNode(gv, "a");;
gap> gv;
<graphviz graph with 1 node and 0 edges>
gap> GraphvizRemoveNode(gv, "a");
<graphviz graph with 0 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:550-551

# doc/_Chapter_Full_Reference.xml:566-573
gap> gv := GraphvizGraph();;
gap> GraphvizAddEdge(gv, "a", "b");;
gap> gv;
<graphviz graph with 2 nodes and 1 edge>
gap> GraphvizRemoveEdges(gv, "a", "b");
<graphviz graph with 2 nodes and 0 edges>

# doc/_Chapter_Full_Reference.xml:596-597

# doc/_Chapter_Full_Reference.xml:615-616

# doc/_Chapter_Full_Reference.xml:631-632

# doc/_Chapter_Full_Reference.xml:648-649

# doc/_Chapter_Full_Reference.xml:668-669

# doc/_Chapter_Full_Reference.xml:683-684

# doc/_Chapter_Full_Reference.xml:799-800

# doc/_Chapter_Full_Reference.xml:817-818

# doc/_Chapter_Full_Reference.xml:833-834

#
gap> STOP_TEST("graphvizforgap01.tst", 1);
